development:
  adapter: async
  :url: redis://localhost:6379/1
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

test:
  adapter: async
  :url: redis://localhost:6379/1
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
  
production:
  adapter: redis
  :host: ec2-34-204-242-91.compute-1.amazonaws.com
  :port: 63359
  :password: p664bda993e12722e54aee4e9853ebd90127ef4b95b3c03d54506e3e0edd658ca
  :url: redis://h:p664bda993e12722e54aee4e9853ebd90127ef4b95b3c03d54506e3e0edd658ca@ec2-34-204-242-91.compute-1.amazonaws.com:63359
  :inline: true
  :timeout: 1
  channel_prefix: Quokka_production
